# Using Pandas to Transform Data

## Objectives: 

-

## Agenda

-

Some great resources:

- https://www.dataschool.io/
- https://realpython.com/fast-flexible-pandas/
- https://chrisalbon.com/#python
- https://pandas.pydata.org/pandas-docs/version/0.15/tutorials.html
- https://medium.com/dunder-data/pandas-tutorials/home

## Pandas

In [2]:
import pandas as pd
import numpy as np

### Create a dataframe from a csv file

In [3]:
movies = pd.read_csv('IMDB-Movie-Data.csv', index_col=0)
movies

,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Rank,,,,,,,,,,,
1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
6,The Great Wall,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.13,42.0
7,La La Land,"Comedy,Drama,Music",A jazz pianist falls for an aspiring actress i...,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",2016,128,8.3,258682,151.06,93.0
8,Mindhorn,Comedy,A has-been actor best known for playing the ti...,Sean Foley,"Essie Davis, Andrea Riseborough, Julian Barrat...",2016,89,6.4,2490,NaN,71.0
9,The Lost City of Z,"Action,Adventure,Biography","A true-life drama, centering on British explor...",James Gray,"Charlie Hunnam, Robert Pattinson, Sienna Mille...",2016,141,7.1,7188,8.01,78.0
10,Passengers,"Adventure,Drama,Romance",A spacecraft traveling to a distant colony pla...,Morten Tyldum,"Jennifer Lawrence, Chris Pratt, Michael Sheen,...",2016,116,7.0,192177,100.01,41.0
11,Fantastic Beasts and Where to Find Them,"Adventure,Family,Fantasy",The adventures of writer Newt Scamander in New...,David Yates,"Eddie Redmayne, Katherine Waterston, Alison Su...",2016,133,7.5,232072,234.02,66.0
12,Hidden Figures,"Biography,Drama,History",The story of a team of female African-American...,Theodore Melfi,"Taraji P. Henson, Octavia Spencer, Janelle Mon...",2016,127,7.8,93103,169.27,74.0
13,Rogue One,"Action,Adventure,Sci-Fi",The Rebel Alliance makes a risky move to steal...,Gareth Edwards,"Felicity Jones, Diego Luna, Alan Tudyk, Donnie...",2016,133,7.9,323118,532.17,65.0
14,Moana,"Animation,Adventure,Comedy","In Ancient Polynesia, when a terrible curse in...",Ron Clements,"Auli'i Cravalho, Dwayne Johnson, Rachel House,...",2016,107,7.7,118151,248.75,81.0
15,Colossal,"Action,Comedy,Drama",Gloria is an out-of-work party girl forced to ...,Nacho Vigalondo,"Anne Hathaway, Jason Sudeikis, Austin Stowell,...",2016,109,6.4,8612,2.87,70.0
16,The Secret Life of Pets,"Animation,Adventure,Comedy",The quiet life of a terrier named Max is upend...,Chris Renaud,"Louis C.K., Eric Stonestreet, Kevin Hart, Lake...",2016,87,6.6,120259,368.31,61.0
17,Hacksaw Ridge,"Biography,Drama,History","WWII American Army Medic Desmond T. Doss, who ...",Mel Gibson,"Andrew Garfield, Sam Worthington, Luke Bracey,...",2016,139,8.2,211760,67.12,71.0
18,Jason Bourne,"Action,Thriller",The CIA's most dangerous former operative is d...,Paul Greengrass,"Matt Damon, Tommy Lee Jones, Alicia Vikander,V...",2016,123,6.7,150823,162.16,58.0
19,Lion,"Biography,Drama",A five-year-old Indian boy gets lost on the st...,Garth Davis,"Dev Patel, Nicole Kidman, Rooney Mara, Sunny P...",2016,118,8.1,102061,51.69,69.0
20,Arrival,"Drama,Mystery,Sci-Fi",When twelve mysterious spacecraft appear aroun...,Denis Villeneuve,"Amy Adams, Jeremy Renner, Forest Whitaker,Mich...",2016,116,8.0,340798,100.50,81.0
21,Gold,"Adventure,Drama,Thriller","Kenny Wells, a prospector desperate for a luck...",Stephen Gaghan,"Matthew McConaughey, Edgar Ramírez, Bryce Dall...",2016,120,6.7,19053,7.22,49.0
22,Manchester by the Sea,Drama,A depressed uncle is asked to take care of his...,Kenneth Lonergan,"Casey Affleck, Michelle Williams, Kyle Chandle...",2016,137,7.9,134213,47.70,96.0
23,Hounds of Love,"Crime,Drama,Horror",A cold-blooded predatory couple while cruising...,Ben Young,"Emma Booth, Ashleigh Cummings, Stephen Curry,S...",2016,108,6.7,1115,NaN,72.0
24,Trolls,"Animation,Adventure,Comedy","After the Bergens invade Troll Village, Poppy,...",Walt Dohrn,"Anna Kendrick, Justin Timberlake,Zooey Deschan...",2016,92,6.5,38552,153.69,56.0
25,Independence Day: Resurgence,"Action,Adventure,Sci-Fi",Two decades after the first Independence Day i...,Roland Emmerich,"Liam Hemsworth, Jeff Goldblum, Bill Pullman,Ma...",2016,120,5.3,127553,103.14,32.0
26,Paris pieds nus,Comedy,Fiona visits Paris for the first time to assis...,Dominique Abel,"Fiona Gordon, Dominique Abel,Emmanuelle Riva, ...",2016,83,6.8,222,NaN,NaN
27,Bahubali: The Beginning,"Action,Adventure,Drama","In ancient India, an adventurous and daring ma...",S.S. Rajamouli,"Prabhas, Rana Daggubati, Anushka Shetty,Tamann...",2015,159,8.3,76193,6.50,NaN
28,Dead Awake,"Horror,Thriller",A young woman must save herself and her friend...,Phillip Guzman,"Jocelin Donahue, Jesse Bradford, Jesse Borrego...",2016,99,4.7,523,0.01,NaN
29,Bad Moms,Comedy,When three overworked and under-appreciated mo...,Jon Lucas,"Mila Kunis, Kathryn Hahn, Kristen Bell,Christi...",2016,100,6.2,66540,113.08,60.0
30,Assassin's Creed,"Action,Adventure,Drama",When Callum Lynch explores the memories of his...,Justin Kurzel,"Michael Fassbender, Marion Cotillard, Jeremy I...",2016,115,5.9,112813,54.65,36.0
...,...,...,...,...,...,...,...,...,...,...,...
971,Texas Chainsaw 3D,"Horror,Thriller",A young woman travels to Texas to collect an i...,John Luessenhop,"Alexandra Daddario, Tania Raymonde, Scott East...",2013,92,4.8,37060,34.33,62.0
972,Disturbia,"Drama,Mystery,Thriller",A teen living under house arrest becomes convi...,D.J. Caruso,"Shia LaBeouf, David Morse, Carrie-Anne Moss, S...",2007,105,6.9,193491,80.05,NaN
973,Rock of Ages,"Comedy,Drama,Musical",A small town girl and a city boy meet on the S...,Adam Shankman,"Julianne Hough, Diego Boneta, Tom Cruise, Alec...",2012,123,5.9,64513,38.51,47.0
974,Scream 4,"Horror,Mystery","Ten years have passed, and Sidney Prescott, wh...",Wes Craven,"Neve Campbell, Courteney Cox, David Arquette, ...",2011,111,6.2,108544,38.18,52.0
975,Queen of Katwe,"Biography,Drama,Sport",A Ugandan girl sees her world rapidly change a...,Mira Nair,"Madina Nalwanga, David Oyelowo, Lupita Nyong'o...",2016,124,7.4,6753,8.81,73.0
976,My Big Fat Greek Wedding 2,"Comedy,Family,Romance",A Portokalos family secret brings the beloved ...,Kirk Jones,"Nia Vardalos, John Corbett, Michael Constantin...",2016,94,6.0,20966,59.57,37.0
977,Dark Places,"Drama,Mystery,Thriller",Libby Day was only eight years old when her fa...,Gilles Paquet-Brenner,"Charlize Theron, Nicholas Hoult, Christina Hen...",2015,113,6.2,31634,NaN,39.0
978,Amateur Night,Comedy,Guy Carter is an award-winning graduate studen...,Lisa Addario,"Jason Biggs, Janet Montgomery,Ashley Tisdale, ...",2016,92,5.0,2229,NaN,38.0
979,It's Only the End of the World,Drama,"Louis (Gaspard Ulliel), a terminally ill write...",Xavier Dolan,"Nathalie Baye, Vincent Cassel, Marion Cotillar...",2016,97,7.0,10658,NaN,48.0
980,The Skin I Live In,"Drama,Thriller","A brilliant plastic surgeon, haunted by past t...",Pedro Almodóvar,"Antonio Banderas, Elena Anaya, Jan Cornet,Mari...",2011,120,7.6,108772,3.19,70.0
981,Miracles from Heaven,"Biography,Drama,Family",A young girl suffering from a rare digestive d...,Patricia Riggen,"Jennifer Garner, Kylie Rogers, Martin Henderso...",2016,109,7.0,12048,61.69,44.0
982,Annie,"Comedy,Drama,Family","A foster kid, who lives with her mean foster m...",Will Gluck,"Quvenzhané Wallis, Cameron Diaz, Jamie Foxx, R...",2014,118,5.3,27312,85.91,33.0
983,Across the Universe,"Drama,Fantasy,Musical",The music of the Beatles and the Vietnam War f...,Julie Taymor,"Evan Rachel Wood, Jim Sturgess, Joe Anderson, ...",2007,133,7.4,95172,24.34,56.0
984,Let's Be Cops,Comedy,Two struggling pals dress as police officers f...,Luke Greenfield,"Jake Johnson, Damon Wayans Jr., Rob Riggle, Ni...",2014,104,6.5,112729,82.39,30.0
985,Max,"Adventure,Family",A Malinois dog that helped American Marines in...,Boaz Yakin,"Thomas Haden Church, Josh Wiggins, Luke Kleint...",2015,111,6.8,21405,42.65,47.0
986,Your Highness,"Adventure,Comedy,Fantasy","When Prince Fabious's bride is kidnapped, he g...",David Gordon Green,"Danny McBride, Natalie Portman, James Franco, ...",2011,102,5.6,87904,21.56,31.0
987,Final Destination 5,"Horror,Thriller",Survivors of a suspension-bridge collapse lear...,Steven Quale,"Nicholas D'Agosto, Emma Bell, Arlen Escarpeta,...",2011,92,5.9,88000,42.58,50.0
988,Endless Love,"Drama,Romance",The story of a privileged girl and a charismat...,Shana Feste,"Gabriella Wilde, Alex Pettyfer, Bruce Greenwoo...",2014,104,6.3,33688,23.39,30.0
989,Martyrs,Horror,A young woman's quest for revenge against the ...,Pascal Laugier,"Morjana Alaoui, Mylène Jampanoï, Catherine Bég...",2008,99,7.1,63785,NaN,89.0
990,Selma,"Biography,Drama,History",A chronicle of Martin Luther King's campaign t...,Ava DuVernay,"David Oyelowo, Carmen Ejogo, Tim Roth, Lorrain...",2014,128,7.5,67637,52.07,NaN
991,Underworld: Rise of the Lycans,"Action,Adventure,Fantasy",An origins story centered on the centuries-old...,Patrick Tatopoulos,"Rhona Mitra, Michael Sheen, Bill Nighy, Steven...",2009,92,6.6,129708,45.80,44.0
992,Taare Zameen Par,"Drama,Family,Music",An eight-year-old boy is thought to be a lazy ...,Aamir Khan,"Darsheel Safary, Aamir Khan, Tanay Chheda, Sac...",2007,165,8.5,102697,1.20,42.0
993,Take Me Home Tonight,"Comedy,Drama,Romance","Four years after graduation, an awkward high s...",Michael Dowse,"Topher Grace, Anna Faris, Dan Fogler, Teresa P...",2011,97,6.3,45419,6.92,NaN
994,Resident Evil: Afterlife,"Action,Adventure,Horror",While still out to destroy the evil Umbrella C...,Paul W.S. Anderson,"Milla Jovovich, Ali Larter, Wentworth Miller,K...",2010,97,5.9,140900,60.13,37.0
995,Project X,Comedy,3 high school seniors throw a birthday party t...,Nima Nourizadeh,"Thomas Mann, Oliver Cooper, Jonathan Daniel Br...",2012,88,6.7,164088,54.72,48.0
996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [4]:
movies.shape

(1000, 11)

In [5]:
pd.set_option('display.max_columns', 20)
pd.set_option('display.max_rows', 100)

In [6]:
movies

,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Rank,,,,,,,,,,,
1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
6,The Great Wall,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.13,42.0
7,La La Land,"Comedy,Drama,Music",A jazz pianist falls for an aspiring actress i...,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",2016,128,8.3,258682,151.06,93.0
8,Mindhorn,Comedy,A has-been actor best known for playing the ti...,Sean Foley,"Essie Davis, Andrea Riseborough, Julian Barrat...",2016,89,6.4,2490,NaN,71.0
9,The Lost City of Z,"Action,Adventure,Biography","A true-life drama, centering on British explor...",James Gray,"Charlie Hunnam, Robert Pattinson, Sienna Mille...",2016,141,7.1,7188,8.01,78.0
10,Passengers,"Adventure,Drama,Romance",A spacecraft traveling to a distant colony pla...,Morten Tyldum,"Jennifer Lawrence, Chris Pratt, Michael Sheen,...",2016,116,7.0,192177,100.01,41.0
11,Fantastic Beasts and Where to Find Them,"Adventure,Family,Fantasy",The adventures of writer Newt Scamander in New...,David Yates,"Eddie Redmayne, Katherine Waterston, Alison Su...",2016,133,7.5,232072,234.02,66.0
12,Hidden Figures,"Biography,Drama,History",The story of a team of female African-American...,Theodore Melfi,"Taraji P. Henson, Octavia Spencer, Janelle Mon...",2016,127,7.8,93103,169.27,74.0
13,Rogue One,"Action,Adventure,Sci-Fi",The Rebel Alliance makes a risky move to steal...,Gareth Edwards,"Felicity Jones, Diego Luna, Alan Tudyk, Donnie...",2016,133,7.9,323118,532.17,65.0
14,Moana,"Animation,Adventure,Comedy","In Ancient Polynesia, when a terrible curse in...",Ron Clements,"Auli'i Cravalho, Dwayne Johnson, Rachel House,...",2016,107,7.7,118151,248.75,81.0
15,Colossal,"Action,Comedy,Drama",Gloria is an out-of-work party girl forced to ...,Nacho Vigalondo,"Anne Hathaway, Jason Sudeikis, Austin Stowell,...",2016,109,6.4,8612,2.87,70.0
16,The Secret Life of Pets,"Animation,Adventure,Comedy",The quiet life of a terrier named Max is upend...,Chris Renaud,"Louis C.K., Eric Stonestreet, Kevin Hart, Lake...",2016,87,6.6,120259,368.31,61.0
17,Hacksaw Ridge,"Biography,Drama,History","WWII American Army Medic Desmond T. Doss, who ...",Mel Gibson,"Andrew Garfield, Sam Worthington, Luke Bracey,...",2016,139,8.2,211760,67.12,71.0
18,Jason Bourne,"Action,Thriller",The CIA's most dangerous former operative is d...,Paul Greengrass,"Matt Damon, Tommy Lee Jones, Alicia Vikander,V...",2016,123,6.7,150823,162.16,58.0
19,Lion,"Biography,Drama",A five-year-old Indian boy gets lost on the st...,Garth Davis,"Dev Patel, Nicole Kidman, Rooney Mara, Sunny P...",2016,118,8.1,102061,51.69,69.0
20,Arrival,"Drama,Mystery,Sci-Fi",When twelve mysterious spacecraft appear aroun...,Denis Villeneuve,"Amy Adams, Jeremy Renner, Forest Whitaker,Mich...",2016,116,8.0,340798,100.50,81.0
21,Gold,"Adventure,Drama,Thriller","Kenny Wells, a prospector desperate for a luck...",Stephen Gaghan,"Matthew McConaughey, Edgar Ramírez, Bryce Dall...",2016,120,6.7,19053,7.22,49.0
22,Manchester by the Sea,Drama,A depressed uncle is asked to take care of his...,Kenneth Lonergan,"Casey Affleck, Michelle Williams, Kyle Chandle...",2016,137,7.9,134213,47.70,96.0
23,Hounds of Love,"Crime,Drama,Horror",A cold-blooded predatory couple while cruising...,Ben Young,"Emma Booth, Ashleigh Cummings, Stephen Curry,S...",2016,108,6.7,1115,NaN,72.0
24,Trolls,"Animation,Adventure,Comedy","After the Bergens invade Troll Village, Poppy,...",Walt Dohrn,"Anna Kendrick, Justin Timberlake,Zooey Deschan...",2016,92,6.5,38552,153.69,56.0
25,Independence Day: Resurgence,"Action,Adventure,Sci-Fi",Two decades after the first Independence Day i...,Roland Emmerich,"Liam Hemsworth, Jeff Goldblum, Bill Pullman,Ma...",2016,120,5.3,127553,103.14,32.0
26,Paris pieds nus,Comedy,Fiona visits Paris for the first time to assis...,Dominique Abel,"Fiona Gordon, Dominique Abel,Emmanuelle Riva, ...",2016,83,6.8,222,NaN,NaN
27,Bahubali: The Beginning,"Action,Adventure,Drama","In ancient India, an adventurous and daring ma...",S.S. Rajamouli,"Prabhas, Rana Daggubati, Anushka Shetty,Tamann...",2015,159,8.3,76193,6.50,NaN
28,Dead Awake,"Horror,Thriller",A young woman must save herself and her friend...,Phillip Guzman,"Jocelin Donahue, Jesse Bradford, Jesse Borrego...",2016,99,4.7,523,0.01,NaN
29,Bad Moms,Comedy,When three overworked and under-appreciated mo...,Jon Lucas,"Mila Kunis, Kathryn Hahn, Kristen Bell,Christi...",2016,100,6.2,66540,113.08,60.0
30,Assassin's Creed,"Action,Adventure,Drama",When Callum Lynch explores the memories of his...,Justin Kurzel,"Michael Fassbender, Marion Cotillard, Jeremy I...",2016,115,5.9,112813,54.65,36.0
31,Why Him?,Comedy,A holiday gathering threatens to go off the ra...,John Hamburg,"Zoey Deutch, James Franco, Tangie Ambrose,Cedr...",2016,111,6.3,48123,60.31,39.0
32,Nocturnal Animals,"Drama,Thriller",A wealthy art gallery owner is haunted by her ...,Tom Ford,"Amy Adams, Jake Gyllenhaal, Michael Shannon, A...",2016,116,7.5,126030,10.64,67.0
33,X-Men: Apocalypse,"Action,Adventure,Sci-Fi",After the re-emergence of the world's first mu...,Bryan Singer,"James McAvoy, Michael Fassbender, Jennifer Law...",2016,144,7.1,275510,155.33,52.0
34,Deadpool,"Action,Adventure,Comedy",A fast-talking mercenary with a morbid sense o...,Tim Miller,"Ryan Reynolds, Morena Baccarin, T.J. Miller, E...",2016,108,8.0,627797,363.02,65.0
35,Resident Evil: The Final Chapter,"Action,Horror,Sci-Fi",Alice returns to where the nightmare began: Th...,Paul W.S. Anderson,"Milla Jovovich, Iain Glen, Ali Larter, Shawn R...",2016,107,5.6,46165,26.84,49.0
36,Captain America: Civil War,"Action,Adventure,Sci-Fi",Political interference in the Avengers' activi...,Anthony Russo,"Chris Evans, Robert Downey Jr.,Scarlett Johans...",2016,147,7.9,411656,408.08,75.0
37,Interstellar,"Adventure,Drama,Sci-Fi",A team of explorers travel through a wormhole ...,Christopher Nolan,"Matthew McConaughey, Anne Hathaway, Jessica Ch...",2014,169,8.6,1047747,187.99,74.0
38,Doctor Strange,"Action,Adventure,Fantasy",While on a journey of physical and spiritual h...,Scott Derrickson,"Benedict Cumberbatch, Chiwetel Ejiofor, Rachel...",2016,115,7.6,293732,232.60,72.0
39,The Magnificent Seven,"Action,Adventure,Western",Seven gunmen in the old west gradually come to...,Antoine Fuqua,"Denzel Washington, Chris Pratt, Ethan Hawke,Vi...",2016,132,6.9,122853,93.38,54.0
40,5- 25- 77,"Comedy,Drama","Alienated, hopeful-filmmaker Pat Johnson's epi...",Patrick Read Johnson,"John Francis Daley, Austin Pendleton, Colleen ...",2007,113,7.1,241,NaN,NaN
41,Sausage Party,"Animation,Adventure,Comedy",A sausage strives to discover the truth about ...,Greg Tiernan,"Seth Rogen, Kristen Wiig, Jonah Hill, Alistair...",2016,89,6.3,120690,97.66,66.0
42,Moonlight,Drama,"A chronicle of the childhood, adolescence and ...",Barry Jenkins,"Mahershala Ali, Shariff Earp, Duan Sanderson, ...",2016,111,7.5,135095,27.85,99.0
43,Don't Fuck in the Woods,Horror,A group of friends are going on a camping trip...,Shawn Burkett,"Brittany Blanton, Ayse Howard, Roman Jossart,N...",2016,73,2.7,496,NaN,NaN
44,The Founder,"Biography,Drama,History","The story of Ray Kroc, a salesman who turned t...",John Lee Hancock,"Michael Keaton, Nick Offerman, John Carroll Ly...",2016,115,7.2,37033,12.79,66.0
45,Lowriders,Drama,A young street artist in East Los Angeles is c...,Ricardo de Montreuil,"Gabriel Chavarria, Demián Bichir, Theo Rossi,T...",2016,99,6.3,279,4.21,57.0
46,Pirates of the Caribbean: On Stranger Tides,"Action,Adventure,Fantasy",Jack Sparrow and Barbossa embark on a quest to...,Rob Marshall,"Johnny Depp, Penélope Cruz, Ian McShane, Geoff...",2011,136,6.7,395025,241.06,45.0
47,Miss Sloane,"Drama,Thriller",In the high-stakes world of political power-br...,John Madden,"Jessica Chastain, Mark Strong, Gugu Mbatha-Raw...",2016,132,7.3,17818,3.44,64.0
48,Fallen,"Adventure,Drama,Fantasy",A young girl finds herself in a reform school ...,Scott Hicks,"Hermione Corfield, Addison Timlin, Joely Richa...",2016,91,5.6,5103,NaN,NaN
49,Star Trek Beyond,"Action,Adventure,Sci-Fi",The USS Enterprise crew explores the furthest ...,Justin Lin,"Chris Pine, Zachary Quinto, Karl Urban, Zoe Sa...",2016,122,7.1,164567,158.80,68.0
50,The Last Face,Drama,A director (Charlize Theron) of an internation...,Sean Penn,"Charlize Theron, Javier Bardem, Adèle Exarchop...",2016,130,3.7,987,NaN,16.0
...,...,...,...,...,...,...,...,...,...,...,...
951,Me and Earl and the Dying Girl,"Comedy,Drama","High schooler Greg, who spends most of his tim...",Alfonso Gomez-Rejon,"Thomas Mann, RJ Cyler, Olivia Cooke, Nick Offe...",2015,105,7.8,92076,6.74,74.0
952,The Descendants,"Comedy,Drama",A land baron tries to reconnect with his two d...,Alexander Payne,"George Clooney, Shailene Woodley, Amara Miller...",2011,115,7.3,211348,82.62,84.0
953,Sex and the City 2,"Comedy,Drama,Romance","While wrestling with the pressures of life, lo...",Michael Patrick King,"Sarah Jessica Parker, Kim Cattrall, Kristin Da...",2010,146,4.3,62403,95.33,27.0
954,The Kings of Summer,"Adventure,Comedy,Drama","Three teenage friends, in the ultimate act of ...",Jordan Vogt-Roberts,"Nick Robinson, Gabriel Basso, Moises Arias,Nic...",2013,95,7.2,65653,1.29,61.0
955,Death Race,"Action,Sci-Fi,Thriller",Ex-con Jensen Ames is forced by the warden of ...,Paul W.S. Anderson,"Jason Statham, Joan Allen, Tyrese Gibson, Ian ...",2008,105,6.4,173731,36.06,43.0
956,That Awkward Moment,"Comedy,Romance",Three best friends find themselves where we've...,Tom Gormican,"Zac Efron, Michael B. Jordan, Miles Teller, Im...",2014,94,6.2,81823,26.05,36.0
957,Legion,"Action,Fantasy,Horror",When a group of strangers at a dusty roadside ...,Scott Stewart,"Paul Bettany, Dennis Quaid, Charles S. Dutton,...",2010,100,5.2,84158,40.17,32.0
958,End of Watch,"Crime,Drama,Thriller","Shot documentary-style, this film follows the ...",David Ayer,"Jake Gyllenhaal, Michael Peña, Anna Kendrick, ...",2012,109,7.7,192190,40.98,68.0
959,3 Days to Kill,"Action,Drama,Thriller",A dying CIA agent trying to reconnect with his...,McG,"Kevin Costner, Hailee Steinfeld, Connie Nielse...",2014,117,6.2,73567,30.69,40.0
960,Lucky Number Slevin,"Crime,Drama,Mystery",A case of mistaken identity lands Slevin into ...,Paul McGuigan,"Josh Hartnett, Ben Kingsley, Morgan Freeman, L...",2006,110,7.8,271940,22.49,53.0
961,Trance,"Crime,Drama,Mystery",An art auctioneer who has become mixed up with...,Danny Boyle,"James McAvoy, Rosario Dawson, Vincent Cassel,D...",2013,101,7.0,97141,2.32,61.0
962,Into the Forest,"Drama,Sci-Fi,Thriller","After a massive power outage, two sisters lear...",Patricia Rozema,"Ellen Page, Evan Rachel Wood, Max Minghella,Ca...",2015,101,5.9,10220,0.01,59.0
963,The Other Boleyn Girl,"Biography,Drama,History",Two sisters contend for the affection of King ...,Justin Chadwick,"Natalie Portman, Scarlett Johansson, Eric Bana...",2008,115,6.7,88260,26.81,50.0
964,I Spit on Your Grave,"Crime,Horror,Thriller",A writer who is brutalized during her cabin re...,Steven R. Monroe,"Sarah Butler, Jeff Branson, Andrew Howard,Dani...",2010,108,6.3,60133,0.09,27.0
965,Custody,Drama,The lives of three women are unexpectedly chan...,James Lapine,"Viola Davis, Hayden Panettiere, Catalina Sandi...",2016,104,6.9,280,NaN,72.0
966,Inland Empire,"Drama,Mystery,Thriller",As an actress starts to adopt the persona of h...,David Lynch,"Laura Dern, Jeremy Irons, Justin Theroux, Karo...",2006,180,7.0,44227,NaN,NaN
967,L'odyssée,"Adventure,Biography",Highly influential and a fearlessly ambitious ...,Jérôme Salle,"Lambert Wilson, Pierre Niney, Audrey Tautou,La...",2016,122,6.7,1810,NaN,70.0
968,The Walk,"Adventure,Biography,Crime","In 1974, high-wire artist Philippe Petit recru...",Robert Zemeckis,"Joseph Gordon-Levitt, Charlotte Le Bon,Guillau...",2015,123,7.3,92378,10.14,NaN
969,Wrecker,"Action,Horror,Thriller",Best friends Emily and Lesley go on a road tri...,Micheal Bafaro,"Anna Hutchison, Andrea Whitburn, Jennifer Koen...",2015,83,3.5,1210,NaN,37.0
970,The Lone Ranger,"Action,Adventure,Western",Native American warrior Tonto recounts the unt...,Gore Verbinski,"Johnny Depp, Armie Hammer, William Fichtner,To...",2013,150,6.5,190855,89.29,NaN
971,Texas Chainsaw 3D,"Horror,Thriller",A young woman travels to Texas to collect an i...,John Luessenhop,"Alexandra Daddario, Tania Raymonde, Scott East...",2013,92,4.8,37060,34.33,62.0
972,Disturbia,"Drama,Mystery,Thriller",A teen living under house arrest becomes convi...,D.J. Caruso,"Shia LaBeouf, David Morse, Carrie-Anne Moss, S...",2007,105,6.9,193491,80.05,NaN
973,Rock of Ages,"Comedy,Drama,Musical",A small town girl and a city boy meet on the S...,Adam Shankman,"Julianne Hough, Diego Boneta, Tom Cruise, Alec...",2012,123,5.9,64513,38.51,47.0
974,Scream 4,"Horror,Mystery","Ten years have passed, and Sidney Prescott, wh...",Wes Craven,"Neve Campbell, Courteney Cox, David Arquette, ...",2011,111,6.2,108544,38.18,52.0
975,Queen of Katwe,"Biography,Drama,Sport",A Ugandan girl sees her world rapidly change a...,Mira Nair,"Madina Nalwanga, David Oyelowo, Lupita Nyong'o...",2016,124,7.4,6753,8.81,73.0
976,My Big Fat Greek Wedding 2,"Comedy,Family,Romance",A Portokalos family secret brings the beloved ...,Kirk Jones,"Nia Vardalos, John Corbett, Michael Constantin...",2016,94,6.0,20966,59.57,37.0
977,Dark Places,"Drama,Mystery,Thriller",Libby Day was only eight years old when her fa...,Gilles Paquet-Brenner,"Charlize Theron, Nicholas Hoult, Christina Hen...",2015,113,6.2,31634,NaN,39.0
978,Amateur Night,Comedy,Guy Carter is an award-winning graduate studen...,Lisa Addario,"Jason Biggs, Janet Montgomery,Ashley Tisdale, ...",2016,92,5.0,2229,NaN,38.0
979,It's Only the End of the World,Drama,"Louis (Gaspard Ulliel), a terminally ill write...",Xavier Dolan,"Nathalie Baye, Vincent Cassel, Marion Cotillar...",2016,97,7.0,10658,NaN,48.0
980,The Skin I Live In,"Drama,Thriller","A brilliant plastic surgeon, haunted by past t...",Pedro Almodóvar,"Antonio Banderas, Elena Anaya, Jan Cornet,Mari...",2011,120,7.6,108772,3.19,70.0
981,Miracles from Heaven,"Biography,Drama,Family",A young girl suffering from a rare digestive d...,Patricia Riggen,"Jennifer Garner, Kylie Rogers, Martin Henderso...",2016,109,7.0,12048,61.69,44.0
982,Annie,"Comedy,Drama,Family","A foster kid, who lives with her mean foster m...",Will Gluck,"Quvenzhané Wallis, Cameron Diaz, Jamie Foxx, R...",2014,118,5.3,27312,85.91,33.0
983,Across the Universe,"Drama,Fantasy,Musical",The music of the Beatles and the Vietnam War f...,Julie Taymor,"Evan Rachel Wood, Jim Sturgess, Joe Anderson, ...",2007,133,7.4,95172,24.34,56.0
984,Let's Be Cops,Comedy,Two struggling pals dress as police officers f...,Luke Greenfield,"Jake Johnson, Damon Wayans Jr., Rob Riggle, Ni...",2014,104,6.5,112729,82.39,30.0
985,Max,"Adventure,Family",A Malinois dog that helped American Marines in...,Boaz Yakin,"Thomas Haden Church, Josh Wiggins, Luke Kleint...",2015,111,6.8,21405,42.65,47.0
986,Your Highness,"Adventure,Comedy,Fantasy","When Prince Fabious's bride is kidnapped, he g...",David Gordon Green,"Danny McBride, Natalie Portman, James Franco, ...",2011,102,5.6,87904,21.56,31.0
987,Final Destination 5,"Horror,Thriller",Survivors of a suspension-bridge collapse lear...,Steven Quale,"Nicholas D'Agosto, Emma Bell, Arlen Escarpeta,...",2011,92,5.9,88000,42.58,50.0
988,Endless Love,"Drama,Romance",The story of a privileged girl and a charismat...,Shana Feste,"Gabriella Wilde, Alex Pettyfer, Bruce Greenwoo...",2014,104,6.3,33688,23.39,30.0
989,Martyrs,Horror,A young woman's quest for revenge against the ...,Pascal Laugier,"Morjana Alaoui, Mylène Jampanoï, Catherine Bég...",2008,99,7.1,63785,NaN,89.0
990,Selma,"Biography,Drama,History",A chronicle of Martin Luther King's campaign t...,Ava DuVernay,"David Oyelowo, Carmen Ejogo, Tim Roth, Lorrain...",2014,128,7.5,67637,52.07,NaN
991,Underworld: Rise of the Lycans,"Action,Adventure,Fantasy",An origins story centered on the centuries-old...,Patrick Tatopoulos,"Rhona Mitra, Michael Sheen, Bill Nighy, Steven...",2009,92,6.6,129708,45.80,44.0
992,Taare Zameen Par,"Drama,Family,Music",An eight-year-old boy is thought to be a lazy ...,Aamir Khan,"Darsheel Safary, Aamir Khan, Tanay Chheda, Sac...",2007,165,8.5,102697,1.20,42.0
993,Take Me Home Tonight,"Comedy,Drama,Romance","Four years after graduation, an awkward high s...",Michael Dowse,"Topher Grace, Anna Faris, Dan Fogler, Teresa P...",2011,97,6.3,45419,6.92,NaN
994,Resident Evil: Afterlife,"Action,Adventure,Horror",While still out to destroy the evil Umbrella C...,Paul W.S. Anderson,"Milla Jovovich, Ali Larter, Wentworth Miller,K...",2010,97,5.9,140900,60.13,37.0
995,Project X,Comedy,3 high school seniors throw a birthday party t...,Nima Nourizadeh,"Thomas Mann, Oliver Cooper, Jonathan Daniel Br...",2012,88,6.7,164088,54.72,48.0
996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

## What is subset selection?
Before we start doing subset selection, it might be good to define what it is. Subset selection is simply selecting particular rows and columns of data from a DataFrame (or Series). This could mean selecting all the rows and some of the columns, some of the rows and all of the columns, or some of each of the rows and columns. 

**Indexers**

There are many ways to select subsets of data, but in this article we will only cover the usage of the square brackets ([]), .loc and .iloc. Collectively, they are called the indexers. These are by far the most common ways to select data.

**What’s the difference between indexing and selecting subsets of data?**

The documentation uses the term indexing frequently. This term is essentially just a one-word phrase to say ‘subset selection’. I prefer the term subset selection as, again, it is more descriptive of what is actually happening. Indexing is also the term used in the official Python documentation.


**A term for just those square brackets**
The term **indexing operator** is used to refer to the square brackets following an object. The .loc and .iloc indexers also use the indexing operator to make selections. I will use the term just the indexing operator to refer to df[]. This will distinguish it from df.loc[] and df.iloc[].

### Indexing Operator

selecting one column as a series

In [7]:
movies['Title']

Rank
1                           Guardians of the Galaxy
2                                        Prometheus
3                                             Split
4                                              Sing
5                                     Suicide Squad
6                                    The Great Wall
7                                        La La Land
8                                          Mindhorn
9                                The Lost City of Z
10                                       Passengers
11          Fantastic Beasts and Where to Find Them
12                                   Hidden Figures
13                                        Rogue One
14                                            Moana
15                                         Colossal
16                          The Secret Life of Pets
17                                    Hacksaw Ridge
18                                     Jason Bourne
19                                             Lion
20                                          Arrival
21                                             Gold
22                            Manchester by the Sea
23                                   Hounds of Love
24                                           Trolls
25                     Independence Day: Resurgence
26                                  Paris pieds nus
27                          Bahubali: The Beginning
28                                       Dead Awake
29                                         Bad Moms
30                                 Assassin's Creed
31                                         Why Him?
32                                Nocturnal Animals
33                                X-Men: Apocalypse
34                                         Deadpool
35                 Resident Evil: The Final Chapter
36                       Captain America: Civil War
37                                     Interstellar
38                                   Doctor Strange
39                            The Magnificent Seven
40                                        5- 25- 77
41                                    Sausage Party
42                                        Moonlight
43                          Don't Fuck in the Woods
44                                      The Founder
45                                        Lowriders
46      Pirates of the Caribbean: On Stranger Tides
47                                      Miss Sloane
48                                           Fallen
49                                 Star Trek Beyond
50                                    The Last Face
                           ...
951                  Me and Earl and the Dying Girl
952                                 The Descendants
953                              Sex and the City 2
954                             The Kings of Summer
955                                      Death Race
956                             That Awkward Moment
957                                          Legion
958                                    End of Watch
959                                  3 Days to Kill
960                             Lucky Number Slevin
961                                          Trance
962                                 Into the Forest
963                           The Other Boleyn Girl
964                            I Spit on Your Grave
965                                         Custody
966                                   Inland Empire
967                                       L'odyssée
968                                        The Walk
969                                         Wrecker
970                                 The Lone Ranger
971                               Texas Chainsaw 3D
972                                       Disturbia
973                                    Rock of Ages
974                                        Scream 4
975                                  Queen of Katwe
976                      My Big Fat Greek Wedding 2
977                                     Dark Places
978                                   Amateur Night
979                  It's Only the End of the World
980                              The Skin I Live In
981                            Miracles from Heaven
982                                           Annie
983                             Across the Universe
984                                   Let's Be Cops
985                                             Max
986                                   Your Highness
987                             Final Destination 5
988                                    Endless Love
989                                         Martyrs
990                                           Selma
991                  Underworld: Rise of the Lycans
992                                Taare Zameen Par
993                            Take Me Home Tonight
994                        Resident Evil: Afterlife
995                                       Project X
996                            Secret in Their Eyes
997                                 Hostel: Part II
998                          Step Up 2: The Streets
999                                    Search Party
1000                                     Nine Lives
Name: Title, Length: 1000, dtype: object

selecting one column as a dataframe

In [8]:
movies[['Title']]

                                            Title
Rank
1                         Guardians of the Galaxy
2                                      Prometheus
3                                           Split
4                                            Sing
5                                   Suicide Squad
6                                  The Great Wall
7                                      La La Land
8                                        Mindhorn
9                              The Lost City of Z
10                                     Passengers
11        Fantastic Beasts and Where to Find Them
12                                 Hidden Figures
13                                      Rogue One
14                                          Moana
15                                       Colossal
16                        The Secret Life of Pets
17                                  Hacksaw Ridge
18                                   Jason Bourne
19                                           Lion
20                                        Arrival
21                                           Gold
22                          Manchester by the Sea
23                                 Hounds of Love
24                                         Trolls
25                   Independence Day: Resurgence
26                                Paris pieds nus
27                        Bahubali: The Beginning
28                                     Dead Awake
29                                       Bad Moms
30                               Assassin's Creed
31                                       Why Him?
32                              Nocturnal Animals
33                              X-Men: Apocalypse
34                                       Deadpool
35               Resident Evil: The Final Chapter
36                     Captain America: Civil War
37                                   Interstellar
38                                 Doctor Strange
39                          The Magnificent Seven
40                                      5- 25- 77
41                                  Sausage Party
42                                      Moonlight
43                        Don't Fuck in the Woods
44                                    The Founder
45                                      Lowriders
46    Pirates of the Caribbean: On Stranger Tides
47                                    Miss Sloane
48                                         Fallen
49                               Star Trek Beyond
50                                  The Last Face
...                                           ...
951                Me and Earl and the Dying Girl
952                               The Descendants
953                            Sex and the City 2
954                           The Kings of Summer
955                                    Death Race
956                           That Awkward Moment
957                                        Legion
958                                  End of Watch
959                                3 Days to Kill
960                           Lucky Number Slevin
961                                        Trance
962                               Into the Forest
963                         The Other Boleyn Girl
964                          I Spit on Your Grave
965                                       Custody
966                                 Inland Empire
967                                     L'odyssée
968                                      The Walk
969                                       Wrecker
970                               The Lone Ranger
971                             Texas Chainsaw 3D
972                                     Disturbia
973                                  Rock of Ages
974                                      Scream 4
975                                Queen of Katwe
976                    My Big Fat Greek Wedding 2
977                                   Dark Places
978                                 Amateur Night
979                It's Only the End of the World
980                            The Skin I Live In
981                          Miracles from Heaven
982                                         Annie
983                           Across the Universe
984                                 Let's Be Cops
985                                           Max
986                                 Your Highness
987                           Final Destination 5
988                                  Endless Love
989                                       Martyrs
990                                         Selma
991                Underworld: Rise of the Lycans
992                              Taare Zameen Par
993                          Take Me Home Tonight
994                      Resident Evil: Afterlife
995                                     Project X
996                          Secret in Their Eyes
997                               Hostel: Part II
998                        Step Up 2: The Streets
999                                  Search Party
1000                                   Nine Lives

[1000 rows x 1 columns]

selecting multiple columns

In [9]:
movies[['Title', 'Year', 'Rating']]

                                            Title  Year  Rating
Rank
1                         Guardians of the Galaxy  2014     8.1
2                                      Prometheus  2012     7.0
3                                           Split  2016     7.3
4                                            Sing  2016     7.2
5                                   Suicide Squad  2016     6.2
6                                  The Great Wall  2016     6.1
7                                      La La Land  2016     8.3
8                                        Mindhorn  2016     6.4
9                              The Lost City of Z  2016     7.1
10                                     Passengers  2016     7.0
11        Fantastic Beasts and Where to Find Them  2016     7.5
12                                 Hidden Figures  2016     7.8
13                                      Rogue One  2016     7.9
14                                          Moana  2016     7.7
15                                       Colossal  2016     6.4
16                        The Secret Life of Pets  2016     6.6
17                                  Hacksaw Ridge  2016     8.2
18                                   Jason Bourne  2016     6.7
19                                           Lion  2016     8.1
20                                        Arrival  2016     8.0
21                                           Gold  2016     6.7
22                          Manchester by the Sea  2016     7.9
23                                 Hounds of Love  2016     6.7
24                                         Trolls  2016     6.5
25                   Independence Day: Resurgence  2016     5.3
26                                Paris pieds nus  2016     6.8
27                        Bahubali: The Beginning  2015     8.3
28                                     Dead Awake  2016     4.7
29                                       Bad Moms  2016     6.2
30                               Assassin's Creed  2016     5.9
31                                       Why Him?  2016     6.3
32                              Nocturnal Animals  2016     7.5
33                              X-Men: Apocalypse  2016     7.1
34                                       Deadpool  2016     8.0
35               Resident Evil: The Final Chapter  2016     5.6
36                     Captain America: Civil War  2016     7.9
37                                   Interstellar  2014     8.6
38                                 Doctor Strange  2016     7.6
39                          The Magnificent Seven  2016     6.9
40                                      5- 25- 77  2007     7.1
41                                  Sausage Party  2016     6.3
42                                      Moonlight  2016     7.5
43                        Don't Fuck in the Woods  2016     2.7
44                                    The Founder  2016     7.2
45                                      Lowriders  2016     6.3
46    Pirates of the Caribbean: On Stranger Tides  2011     6.7
47                                    Miss Sloane  2016     7.3
48                                         Fallen  2016     5.6
49                               Star Trek Beyond  2016     7.1
50                                  The Last Face  2016     3.7
...                                           ...   ...     ...
951                Me and Earl and the Dying Girl  2015     7.8
952                               The Descendants  2011     7.3
953                            Sex and the City 2  2010     4.3
954                           The Kings of Summer  2013     7.2
955                                    Death Race  2008     6.4
956                           That Awkward Moment  2014     6.2
957                                        Legion  2010     5.2
958                                  End of Watch  2012     7.7
959                                3 Days to Kill  2014     6.2
960                           Lucky Number Slevin  2006     7.8
961                                        Trance  2013     7.0
962                               Into the Forest  2015     5.9
963                         The Other Boleyn Girl  2008     6.7
964                          I Spit on Your Grave  2010     6.3
965                                       Custody  2016     6.9
966                                 Inland Empire  2006     7.0
967                                     L'odyssée  2016     6.7
968                                      The Walk  2015     7.3
969                                       Wrecker  2015     3.5
970                               The Lone Ranger  2013     6.5
971                             Texas Chainsaw 3D  2013     4.8
972                                     Disturbia  2007     6.9
973                                  Rock of Ages  2012     5.9
974                                      Scream 4  2011     6.2
975                                Queen of Katwe  2016     7.4
976                    My Big Fat Greek Wedding 2  2016     6.0
977                                   Dark Places  2015     6.2
978                                 Amateur Night  2016     5.0
979                It's Only the End of the World  2016     7.0
980                            The Skin I Live In  2011     7.6
981                          Miracles from Heaven  2016     7.0
982                                         Annie  2014     5.3
983                           Across the Universe  2007     7.4
984                                 Let's Be Cops  2014     6.5
985                                           Max  2015     6.8
986                                 Your Highness  2011     5.6
987                           Final Destination 5  2011     5.9
988                                  Endless Love  2014     6.3
989                                       Martyrs  2008     7.1
990                                         Selma  2014     7.5
991                Underworld: Rise of the Lycans  2009     6.6
992                              Taare Zameen Par  2007     8.5
993                          Take Me Home Tonight  2011     6.3
994                      Resident Evil: Afterlife  2010     5.9
995                                     Project X  2012     6.7
996                          Secret in Their Eyes  2015     6.2
997                               Hostel: Part II  2007     5.5
998                        Step Up 2: The Streets  2008     6.2
999                                  Search Party  2014     5.6
1000                                   Nine Lives  2016     5.3

[1000 rows x 3 columns]

In [10]:
#using the indexing operator to select rows
movies[3:6]

,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Rank,,,,,,,,,,,
4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
6,The Great Wall,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.13,42.0

### Summary: Indexing Operator
- Its primary purpose is to select columns by the column names
- Select a single column as a Series by passing the column name directly to it: df['col_name']
- Select multiple columns as a DataFrame by passing a list to it: df[['col_name1', 'col_name2']]
- You actually can select rows with it, but this is confusing and not used often.

### .loc
The .loc indexer selects data in a different way than just the indexing operator. It can select subsets of rows or columns. It can also simultaneously select subsets of rows and columns. Most importantly, it only selects data by the LABEL of the rows and columns.

In [11]:
movies_title = movies.set_index('Title')

In [12]:
movies_title.head()

,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,
Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [19]:
movies_title.loc['Sing']

Genre                                           Animation,Comedy,Family
Description           In a city of humanoid animals, a hustling thea...
Director                                           Christophe Lourdelet
Actors                Matthew McConaughey,Reese Witherspoon, Seth Ma...
Year                                                               2016
Runtime (Minutes)                                                   108
Rating                                                              7.2
Votes                                                             60545
Revenue (Millions)                                               270.32
Metascore                                                            59
Name: Sing, dtype: object

In [14]:
movies_title.loc[['Prometheus','Sing']]

,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,
Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0

In [15]:
movies_title.loc['Prometheus':'Sing']

,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,
Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0

In [17]:
movies_title.loc[ 'Sing':]

,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,
Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
The Great Wall,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.13,42.0
La La Land,"Comedy,Drama,Music",A jazz pianist falls for an aspiring actress i...,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",2016,128,8.3,258682,151.06,93.0
Mindhorn,Comedy,A has-been actor best known for playing the ti...,Sean Foley,"Essie Davis, Andrea Riseborough, Julian Barrat...",2016,89,6.4,2490,NaN,71.0
The Lost City of Z,"Action,Adventure,Biography","A true-life drama, centering on British explor...",James Gray,"Charlie Hunnam, Robert Pattinson, Sienna Mille...",2016,141,7.1,7188,8.01,78.0
Passengers,"Adventure,Drama,Romance",A spacecraft traveling to a distant colony pla...,Morten Tyldum,"Jennifer Lawrence, Chris Pratt, Michael Sheen,...",2016,116,7.0,192177,100.01,41.0
Fantastic Beasts and Where to Find Them,"Adventure,Family,Fantasy",The adventures of writer Newt Scamander in New...,David Yates,"Eddie Redmayne, Katherine Waterston, Alison Su...",2016,133,7.5,232072,234.02,66.0
Hidden Figures,"Biography,Drama,History",The story of a team of female African-American...,Theodore Melfi,"Taraji P. Henson, Octavia Spencer, Janelle Mon...",2016,127,7.8,93103,169.27,74.0
Rogue One,"Action,Adventure,Sci-Fi",The Rebel Alliance makes a risky move to steal...,Gareth Edwards,"Felicity Jones, Diego Luna, Alan Tudyk, Donnie...",2016,133,7.9,323118,532.17,65.0
Moana,"Animation,Adventure,Comedy","In Ancient Polynesia, when a terrible curse in...",Ron Clements,"Auli'i Cravalho, Dwayne Johnson, Rachel House,...",2016,107,7.7,118151,248.75,81.0
Colossal,"Action,Comedy,Drama",Gloria is an out-of-work party girl forced to ...,Nacho Vigalondo,"Anne Hathaway, Jason Sudeikis, Austin Stowell,...",2016,109,6.4,8612,2.87,70.0
The Secret Life of Pets,"Animation,Adventure,Comedy",The quiet life of a terrier named Max is upend...,Chris Renaud,"Louis C.K., Eric Stonestreet, Kevin Hart, Lake...",2016,87,6.6,120259,368.31,61.0
Hacksaw Ridge,"Biography,Drama,History","WWII American Army Medic Desmond T. Doss, who ...",Mel Gibson,"Andrew Garfield, Sam Worthington, Luke Bracey,...",2016,139,8.2,211760,67.12,71.0
Jason Bourne,"Action,Thriller",The CIA's most dangerous former operative is d...,Paul Greengrass,"Matt Damon, Tommy Lee Jones, Alicia Vikander,V...",2016,123,6.7,150823,162.16,58.0
Lion,"Biography,Drama",A five-year-old Indian boy gets lost on the st...,Garth Davis,"Dev Patel, Nicole Kidman, Rooney Mara, Sunny P...",2016,118,8.1,102061,51.69,69.0
Arrival,"Drama,Mystery,Sci-Fi",When twelve mysterious spacecraft appear aroun...,Denis Villeneuve,"Amy Adams, Jeremy Renner, Forest Whitaker,Mich...",2016,116,8.0,340798,100.50,81.0
Gold,"Adventure,Drama,Thriller","Kenny Wells, a prospector desperate for a luck...",Stephen Gaghan,"Matthew McConaughey, Edgar Ramírez, Bryce Dall...",2016,120,6.7,19053,7.22,49.0
Manchester by the Sea,Drama,A depressed uncle is asked to take care of his...,Kenneth Lonergan,"Casey Affleck, Michelle Williams, Kyle Chandle...",2016,137,7.9,134213,47.70,96.0
Hounds of Love,"Crime,Drama,Horror",A cold-blooded predatory couple while cruising...,Ben Young,"Emma Booth, Ashleigh Cummings, Stephen Curry,S...",2016,108,6.7,1115,NaN,72.0
Trolls,"Animation,Adventure,Comedy","After the Bergens invade Troll Village, Poppy,...",Walt Dohrn,"Anna Kendrick, Justin Timberlake,Zooey Deschan...",2016,92,6.5,38552,153.69,56.0
Independence Day: Resurgence,"Action,Adventure,Sci-Fi",Two decades after the first Independence Day i...,Roland Emmerich,"Liam Hemsworth, Jeff Goldblum, Bill Pullman,Ma...",2016,120,5.3,127553,103.14,32.0
Paris pieds nus,Comedy,Fiona visits Paris for the first time to assis...,Dominique Abel,"Fiona Gordon, Dominique Abel,Emmanuelle Riva, ...",2016,83,6.8,222,NaN,NaN
Bahubali: The Beginning,"Action,Adventure,Drama","In ancient India, an adventurous and daring ma...",S.S. Rajamouli,"Prabhas, Rana Daggubati, Anushka Shetty,Tamann...",2015,159,8.3,76193,6.50,NaN
Dead Awake,"Horror,Thriller",A young woman must save herself and her friend...,Phillip Guzman,"Jocelin Donahue, Jesse Bradford, Jesse Borrego...",2016,99,4.7,523,0.01,NaN
Bad Moms,Comedy,When three overworked and under-appreciated mo...,Jon Lucas,"Mila Kunis, Kathryn Hahn, Kristen Bell,Christi...",2016,100,6.2,66540,113.08,60.0
Assassin's Creed,"Action,Adventure,Drama",When Callum Lynch explores the memories of his...,Justin Kurzel,"Michael Fassbender, Marion Cotillard, Jeremy I...",2016,115,5.9,112813,54.65,36.0
Why Him?,Comedy,A holiday gathering threatens to go off the ra...,John Hamburg,"Zoey Deutch, James Franco, Tangie Ambrose,Cedr...",2016,111,6.3,48123,60.31,39.0
Nocturnal Animals,"Drama,Thriller",A wealthy art gallery owner is haunted by her ...,Tom Ford,"Amy Adams, Jake Gyllenhaal, Michael Shannon, A...",2016,116,7.5,126030,10.64,67.0
X-Men: Apocalypse,"Action,Adventure,Sci-Fi",After the re-emergence of the world's first mu...,Bryan Singer,"James McAvoy, Michael Fassbender, Jennifer Law...",2016,144,7.1,275510,155.33,52.0
Deadpool,"Action,Adventure,Comedy",A fast-talking mercenary with a morbid sense o...,Tim Miller,"Ryan Reynolds, Morena Baccarin, T.J. Miller, E...",2016,108,8.0,627797,363.02,65.0
Resident Evil: The Final Chapter,"Action,Horror,Sci-Fi",Alice returns to where the nightmare began: Th...,Paul W.S. Anderson,"Milla Jovovich, Iain Glen, Ali Larter, Shawn R...",2016,107,5.6,46165,26.84,49.0
Captain America: Civil War,"Action,Adventure,Sci-Fi",Political interference in the Avengers' activi...,Anthony Russo,"Chris Evans, Robert Downey Jr.,Scarlett Johans...",2016,147,7.9,411656,408.08,75.0
Interstellar,"Adventure,Drama,Sci-Fi",A team of explorers travel through a wormhole ...,Christopher Nolan,"Matthew McConaughey, Anne Hathaway, Jessica Ch...",2014,169,8.6,1047747,187.99,74.0
Doctor Strange,"Action,Adventure,Fantasy",While on a journey of physical and spiritual h...,Scott Derrickson,"Benedict Cumberbatch, Chiwetel Ejiofor, Rachel...",2016,115,7.6,293732,232.60,72.0
The Magnificent Seven,"Action,Adventure,Western",Seven gunmen in the old west gradually come to...,Antoine Fuqua,"Denzel Washington, Chris Pratt, Ethan Hawke,Vi...",2016,132,6.9,122853,93.38,54.0
5- 25- 77,"Comedy,Drama","Alienated, hopeful-filmmaker Pat Johnson's epi...",Patrick Read Johnson,"John Francis Daley, Austin Pendleton, Colleen ...",2007,113,7.1,241,NaN,NaN
Sausage Party,"Animation,Adventure,Comedy",A sausage strives to discover the truth about ...,Greg Tiernan,"Seth Rogen, Kristen Wiig, Jonah Hill, Alistair...",2016,89,6.3,120690,97.66,66.0
Moonlight,Drama,"A chronicle of the childhood, adolescence and ...",Barry Jenkins,"Mahershala Ali, Shariff Earp, Duan Sanderson, ...",2016,111,7.5,135095,27.85,99.0
Don't Fuck in the Woods,Horror,A group of friends are going on a camping trip...,Shawn Burkett,"Brittany Blanton, Ayse Howard, Roman Jossart,N...",2016,73,2.7,496,NaN,NaN
The Founder,"Biography,Drama,History","The story of Ray Kroc, a salesman who turned t...",John Lee Hancock,"Michael Keaton, Nick Offerman, John Carroll Ly...",2016,115,7.2,37033,12.79,66.0
Lowriders,Drama,A young street artist in East Los Angeles is c...,Ricardo de Montreuil,"Gabriel Chavarria, Demián Bichir, Theo Rossi,T...",2016,99,6.3,279,4.21,57.0
Pirates of the Caribbean: On Stranger Tides,"Action,Adventure,Fantasy",Jack Sparrow and Barbossa embark on a quest to...,Rob Marshall,"Johnny Depp, Penélope Cruz, Ian McShane, Geoff...",2011,136,6.7,395025,241.06,45.0
Miss Sloane,"Drama,Thriller",In the high-stakes world of political power-br...,John Madden,"Jessica Chastain, Mark Strong, Gugu Mbatha-Raw...",2016,132,7.3,17818,3.44,64.0
Fallen,"Adventure,Drama,Fantasy",A young girl finds herself in a reform school ...,Scott Hicks,"Hermione Corfield, Addison Timlin, Joely Richa...",2016,91,5.6,5103,NaN,NaN
Star Trek Beyond,"Action,Adventure,Sci-Fi",The USS Enterprise crew explores the furthest ...,Justin Lin,"Chris Pine, Zachary Quinto, Karl Urban, Zoe Sa...",2016,122,7.1,164567,158.80,68.0
The Last Face,Drama,A director (Charlize Theron) of an internation...,Sean Penn,"Charlize Theron, Javier Bardem, Adèle Exarchop...",2016,130,3.7,987,NaN,16.0
Star Wars: Episode VII - The Force Awakens,"Action,Adventure,Fantasy",Three decades after the defeat of the Galactic...,J.J. Abrams,"Daisy Ridley, John Boyega, Oscar Isaac, Domhna...",2015,136,8.1,661608,936.63,81.0
Underworld: Blood Wars,"Action,Adventure,Fantasy","Vampire death dealer, Selene (Kate Beckinsale)...",Anna Foerster,"Kate Beckinsale, Theo James, Tobias Menzies, L...",2016,91,5.8,41362,30.35,23.0
Mother's Day,"Comedy,Drama",Three generations come together in the week le...,Garry Marshall,"Jennifer Aniston, Kate Hudson, Julia Roberts, ...",2016,118,5.6,20221,32.46,18.0
...,...,...,...,...,...,...,...,...,...,...
Me and Earl and the Dying Girl,"Comedy,Drama","High schooler Greg, who spends most of his tim...",Alfonso Gomez-Rejon,"Thomas Mann, RJ Cyler, Olivia Cooke, Nick Offe...",2015,105,7.8,92076,6.74,74.0
The Descendants,"Comedy,Drama",A land baron tries to reconnect with his two d...,Alexander Payne,"George Clooney, Shailene Woodley, Amara Miller...",2011,115,7.3,211348,82.62,84.0
Sex and the City 2,"Comedy,Drama,Romance","While wrestling with the pressures of life, lo...",Michael Patrick King,"Sarah Jessica Parker, Kim Cattrall, Kristin Da...",2010,146,4.3,62403,95.33,27.0
The Kings of Summer,"Adventure,Comedy,Drama","Three teenage friends, in the ultimate act of ...",Jordan Vogt-Roberts,"Nick Robinson, Gabriel Basso, Moises Arias,Nic...",2013,95,7.2,65653,1.29,61.0
Death Race,"Action,Sci-Fi,Thriller",Ex-con Jensen Ames is forced by the warden of ...,Paul W.S. Anderson,"Jason Statham, Joan Allen, Tyrese Gibson, Ian ...",2008,105,6.4,173731,36.06,43.0
That Awkward Moment,"Comedy,Romance",Three best friends find themselves where we've...,Tom Gormican,"Zac Efron, Michael B. Jordan, Miles Teller, Im...",2014,94,6.2,81823,26.05,36.0
Legion,"Action,Fantasy,Horror",When a group of strangers at a dusty roadside ...,Scott Stewart,"Paul Bettany, Dennis Quaid, Charles S. Dutton,...",2010,100,5.2,84158,40.17,32.0
End of Watch,"Crime,Drama,Thriller","Shot documentary-style, this film follows the ...",David Ayer,"Jake Gyllenhaal, Michael Peña, Anna Kendrick, ...",2012,109,7.7,192190,40.98,68.0
3 Days to Kill,"Action,Drama,Thriller",A dying CIA agent trying to reconnect with his...,McG,"Kevin Costner, Hailee Steinfeld, Connie Nielse...",2014,117,6.2,73567,30.69,40.0
Lucky Number Slevin,"Crime,Drama,Mystery",A case of mistaken identity lands Slevin into ...,Paul McGuigan,"Josh Hartnett, Ben Kingsley, Morgan Freeman, L...",2006,110,7.8,271940,22.49,53.0
Trance,"Crime,Drama,Mystery",An art auctioneer who has become mixed up with...,Danny Boyle,"James McAvoy, Rosario Dawson, Vincent Cassel,D...",2013,101,7.0,97141,2.32,61.0
Into the Forest,"Drama,Sci-Fi,Thriller","After a massive power outage, two sisters lear...",Patricia Rozema,"Ellen Page, Evan Rachel Wood, Max Minghella,Ca...",2015,101,5.9,10220,0.01,59.0
The Other Boleyn Girl,"Biography,Drama,History",Two sisters contend for the affection of King ...,Justin Chadwick,"Natalie Portman, Scarlett Johansson, Eric Bana...",2008,115,6.7,88260,26.81,50.0
I Spit on Your Grave,"Crime,Horror,Thriller",A writer who is brutalized during her cabin re...,Steven R. Monroe,"Sarah Butler, Jeff Branson, Andrew Howard,Dani...",2010,108,6.3,60133,0.09,27.0
Custody,Drama,The lives of three women are unexpectedly chan...,James Lapine,"Viola Davis, Hayden Panettiere, Catalina Sandi...",2016,104,6.9,280,NaN,72.0
Inland Empire,"Drama,Mystery,Thriller",As an actress starts to adopt the persona of h...,David Lynch,"Laura Dern, Jeremy Irons, Justin Theroux, Karo...",2006,180,7.0,44227,NaN,NaN
L'odyssée,"Adventure,Biography",Highly influential and a fearlessly ambitious ...,Jérôme Salle,"Lambert Wilson, Pierre Niney, Audrey Tautou,La...",2016,122,6.7,1810,NaN,70.0
The Walk,"Adventure,Biography,Crime","In 1974, high-wire artist Philippe Petit recru...",Robert Zemeckis,"Joseph Gordon-Levitt, Charlotte Le Bon,Guillau...",2015,123,7.3,92378,10.14,NaN
Wrecker,"Action,Horror,Thriller",Best friends Emily and Lesley go on a road tri...,Micheal Bafaro,"Anna Hutchison, Andrea Whitburn, Jennifer Koen...",2015,83,3.5,1210,NaN,37.0
The Lone Ranger,"Action,Adventure,Western",Native American warrior Tonto recounts the unt...,Gore Verbinski,"Johnny Depp, Armie Hammer, William Fichtner,To...",2013,150,6.5,190855,89.29,NaN
Texas Chainsaw 3D,"Horror,Thriller",A young woman travels to Texas to collect an i...,John Luessenhop,"Alexandra Daddario, Tania Raymonde, Scott East...",2013,92,4.8,37060,34.33,62.0
Disturbia,"Drama,Mystery,Thriller",A teen living under house arrest becomes convi...,D.J. Caruso,"Shia LaBeouf, David Morse, Carrie-Anne Moss, S...",2007,105,6.9,193491,80.05,NaN
Rock of Ages,"Comedy,Drama,Musical",A small town girl and a city boy meet on the S...,Adam Shankman,"Julianne Hough, Diego Boneta, Tom Cruise, Alec...",2012,123,5.9,64513,38.51,47.0
Scream 4,"Horror,Mystery","Ten years have passed, and Sidney Prescott, wh...",Wes Craven,"Neve Campbell, Courteney Cox, David Arquette, ...",2011,111,6.2,108544,38.18,52.0
Queen of Katwe,"Biography,Drama,Sport",A Ugandan girl sees her world rapidly change a...,Mira Nair,"Madina Nalwanga, David Oyelowo, Lupita Nyong'o...",2016,124,7.4,6753,8.81,73.0
My Big Fat Greek Wedding 2,"Comedy,Family,Romance",A Portokalos family secret brings the beloved ...,Kirk Jones,"Nia Vardalos, John Corbett, Michael Constantin...",2016,94,6.0,20966,59.57,37.0
Dark Places,"Drama,Mystery,Thriller",Libby Day was only eight years old when her fa...,Gilles Paquet-Brenner,"Charlize Theron, Nicholas Hoult, Christina Hen...",2015,113,6.2,31634,NaN,39.0
Amateur Night,Comedy,Guy Carter is an award-winning graduate studen...,Lisa Addario,"Jason Biggs, Janet Montgomery,Ashley Tisdale, ...",2016,92,5.0,2229,NaN,38.0
It's Only the End of the World,Drama,"Louis (Gaspard Ulliel), a terminally ill write...",Xavier Dolan,"Nathalie Baye, Vincent Cassel, Marion Cotillar...",2016,97,7.0,10658,NaN,48.0
The Skin I Live In,"Drama,Thriller","A brilliant plastic surgeon, haunted by past t...",Pedro Almodóvar,"Antonio Banderas, Elena Anaya, Jan Cornet,Mari...",2011,120,7.6,108772,3.19,70.0
Miracles from Heaven,"Biography,Drama,Family",A young girl suffering from a rare digestive d...,Patricia Riggen,"Jennifer Garner, Kylie Rogers, Martin Henderso...",2016,109,7.0,12048,61.69,44.0
Annie,"Comedy,Drama,Family","A foster kid, who lives with her mean foster m...",Will Gluck,"Quvenzhané Wallis, Cameron Diaz, Jamie Foxx, R...",2014,118,5.3,27312,85.91,33.0
Across the Universe,"Drama,Fantasy,Musical",The music of the Beatles and the Vietnam War f...,Julie Taymor,"Evan Rachel Wood, Jim Sturgess, Joe Anderson, ...",2007,133,7.4,95172,24.34,56.0
Let's Be Cops,Comedy,Two struggling pals dress as police officers f...,Luke Greenfield,"Jake Johnson, Damon Wayans Jr., Rob Riggle, Ni...",2014,104,6.5,112729,82.39,30.0
Max,"Adventure,Family",A Malinois dog that helped American Marines in...,Boaz Yakin,"Thomas Haden Church, Josh Wiggins, Luke Kleint...",2015,111,6.8,21405,42.65,47.0
Your Highness,"Adventure,Comedy,Fantasy","When Prince Fabious's bride is kidnapped, he g...",David Gordon Green,"Danny McBride, Natalie Portman, James Franco, ...",2011,102,5.6,87904,21.56,31.0
Final Destination 5,"Horror,Thriller",Survivors of a suspension-bridge collapse lear...,Steven Quale,"Nicholas D'Agosto, Emma Bell, Arlen Escarpeta,...",2011,92,5.9,88000,42.58,50.0
Endless Love,"Drama,Romance",The story of a privileged girl and a charismat...,Shana Feste,"Gabriella Wilde, Alex Pettyfer, Bruce Greenwoo...",2014,104,6.3,33688,23.39,30.0
Martyrs,Horror,A young woman's quest for revenge against the ...,Pascal Laugier,"Morjana Alaoui, Mylène Jampanoï, Catherine Bég...",2008,99,7.1,63785,NaN,89.0
Selma,"Biography,Drama,History",A chronicle of Martin Luther King's campaign t...,Ava DuVernay,"David Oyelowo, Carmen Ejogo, Tim Roth, Lorrain...",2014,128,7.5,67637,52.07,NaN
Underworld: Rise of the Lycans,"Action,Adventure,Fantasy",An origins story centered on the centuries-old...,Patrick Tatopoulos,"Rhona Mitra, Michael Sheen, Bill Nighy, Steven...",2009,92,6.6,129708,45.80,44.0
Taare Zameen Par,"Drama,Family,Music",An eight-year-old boy is thought to be a lazy ...,Aamir Khan,"Darsheel Safary, Aamir Khan, Tanay Chheda, Sac...",2007,165,8.5,102697,1.20,42.0
Take Me Home Tonight,"Comedy,Drama,Romance","Four years after graduation, an awkward high s...",Michael Dowse,"Topher Grace, Anna Faris, Dan Fogler, Teresa P...",2011,97,6.3,45419,6.92,NaN
Resident Evil: Afterlife,"Action,Adventure,Horror",While still out to destroy the evil Umbrella C...,Paul W.S. Anderson,"Milla Jovovich, Ali Larter, Wentworth Miller,K...",2010,97,5.9,140900,60.13,37.0
Project X,Comedy,3 high school seniors throw a birthday party t...,Nima Nourizadeh,"Thomas Mann, Oliver Cooper, Jonathan Daniel Br...",2012,88,6.7,164088,54.72,48.0
Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

**Selecting rows and columns simultaneously with .loc**

Unlike just the indexing operator, it is possible to select rows and columns simultaneously with .loc. You do it by separating your row and column selections by a comma. It will look something like this:

`df.loc[row_selection, column_selection]`

In [20]:
movies.loc[1:3, ['Title','Genre', 'Year']]

                        Title                     Genre  Year
Rank
1     Guardians of the Galaxy   Action,Adventure,Sci-Fi  2014
2                  Prometheus  Adventure,Mystery,Sci-Fi  2012
3                       Split           Horror,Thriller  2016

In [21]:
movies_title.loc['Prometheus':'Sing', ['Genre', 'Year']]

                               Genre  Year
Title
Prometheus  Adventure,Mystery,Sci-Fi  2012
Split                Horror,Thriller  2016
Sing         Animation,Comedy,Family  2016

In [22]:
movies_title.loc[['Prometheus','Sing'], ['Genre', 'Year']]

                               Genre  Year
Title
Prometheus  Adventure,Mystery,Sci-Fi  2012
Sing         Animation,Comedy,Family  2016

In [26]:
movies_title.loc[: , ['Genre', 'Year'] ]

                                                                  Genre  Year
Title
Guardians of the Galaxy                         Action,Adventure,Sci-Fi  2014
Prometheus                                     Adventure,Mystery,Sci-Fi  2012
Split                                                   Horror,Thriller  2016
Sing                                            Animation,Comedy,Family  2016
Suicide Squad                                  Action,Adventure,Fantasy  2016
The Great Wall                                 Action,Adventure,Fantasy  2016
La La Land                                           Comedy,Drama,Music  2016
Mindhorn                                                         Comedy  2016
The Lost City of Z                           Action,Adventure,Biography  2016
Passengers                                      Adventure,Drama,Romance  2016
Fantastic Beasts and Where to Find Them        Adventure,Family,Fantasy  2016
Hidden Figures                                  Biography,Drama,History  2016
Rogue One                                       Action,Adventure,Sci-Fi  2016
Moana                                        Animation,Adventure,Comedy  2016
Colossal                                            Action,Comedy,Drama  2016
The Secret Life of Pets                      Animation,Adventure,Comedy  2016
Hacksaw Ridge                                   Biography,Drama,History  2016
Jason Bourne                                            Action,Thriller  2016
Lion                                                    Biography,Drama  2016
Arrival                                            Drama,Mystery,Sci-Fi  2016
Gold                                           Adventure,Drama,Thriller  2016
Manchester by the Sea                                             Drama  2016
Hounds of Love                                       Crime,Drama,Horror  2016
Trolls                                       Animation,Adventure,Comedy  2016
Independence Day: Resurgence                    Action,Adventure,Sci-Fi  2016
Paris pieds nus                                                  Comedy  2016
Bahubali: The Beginning                          Action,Adventure,Drama  2015
Dead Awake                                              Horror,Thriller  2016
Bad Moms                                                         Comedy  2016
Assassin's Creed                                 Action,Adventure,Drama  2016
Why Him?                                                         Comedy  2016
Nocturnal Animals                                        Drama,Thriller  2016
X-Men: Apocalypse                               Action,Adventure,Sci-Fi  2016
Deadpool                                        Action,Adventure,Comedy  2016
Resident Evil: The Final Chapter                   Action,Horror,Sci-Fi  2016
Captain America: Civil War                      Action,Adventure,Sci-Fi  2016
Interstellar                                     Adventure,Drama,Sci-Fi  2014
Doctor Strange                                 Action,Adventure,Fantasy  2016
The Magnificent Seven                          Action,Adventure,Western  2016
5- 25- 77                                                  Comedy,Drama  2007
Sausage Party                                Animation,Adventure,Comedy  2016
Moonlight                                                         Drama  2016
Don't Fuck in the Woods                                          Horror  2016
The Founder                                     Biography,Drama,History  2016
Lowriders                                                         Drama  2016
Pirates of the Caribbean: On Stranger Tides    Action,Adventure,Fantasy  2011
Miss Sloane                                              Drama,Thriller  2016
Fallen                                          Adventure,Drama,Fantasy  2016
Star Trek Beyond                                Action,Adventure,Sci-Fi  2016
The Last Face                                                     Drama  2016
...                                                                 ...   ...
Me and Earl and the Dying Girl                             Comedy,Drama  2015
The Descendants                                            Comedy,Drama  2011
Sex and the City 2                                 Comedy,Drama,Romance  2010
The Kings of Summer                              Adventure,Comedy,Drama  2013
Death Race                                       Action,Sci-Fi,Thriller  2008
That Awkward Moment                                      Comedy,Romance  2014
Legion                                            Action,Fantasy,Horror  2010
End of Watch                                       Crime,Drama,Thriller  2012
3 Days to Kill                                    Action,Drama,Thriller  2014
Lucky Number Slevin                                 Crime,Drama,Mystery  2006
Trance                                              Crime,Drama,Mystery  2013
Into the Forest                                   Drama,Sci-Fi,Thriller  2015
The Other Boleyn Girl                           Biography,Drama,History  2008
I Spit on Your Grave                              Crime,Horror,Thriller  2010
Custody                                                           Drama  2016
Inland Empire                                    Drama,Mystery,Thriller  2006
L'odyssée                                           Adventure,Biography  2016
The Walk                                      Adventure,Biography,Crime  2015
Wrecker                                          Action,Horror,Thriller  2015
The Lone Ranger                                Action,Adventure,Western  2013
Texas Chainsaw 3D                                       Horror,Thriller  2013
Disturbia                                        Drama,Mystery,Thriller  2007
Rock of Ages                                       Comedy,Drama,Musical  2012
Scream 4                                                 Horror,Mystery  2011
Queen of Katwe                                    Biography,Drama,Sport  2016
My Big Fat Greek Wedding 2                        Comedy,Family,Romance  2016
Dark Places                                      Drama,Mystery,Thriller  2015
Amateur Night                                                    Comedy  2016
It's Only the End of the World                                    Drama  2016
The Skin I Live In                                       Drama,Thriller  2011
Miracles from Heaven                             Biography,Drama,Family  2016
Annie                                               Comedy,Drama,Family  2014
Across the Universe                               Drama,Fantasy,Musical  2007
Let's Be Cops                                                    Comedy  2014
Max                                                    Adventure,Family  2015
Your Highness                                  Adventure,Comedy,Fantasy  2011
Final Destination 5                                     Horror,Thriller  2011
Endless Love                                              Drama,Romance  2014
Martyrs                                                          Horror  2008
Selma                                           Biography,Drama,History  2014
Underworld: Rise of the Lycans                 Action,Adventure,Fantasy  2009
Taare Zameen Par                                     Drama,Family,Music  2007
Take Me Home Tonight                               Comedy,Drama,Romance  2011
Resident Evil: Afterlife                        Action,Adventure,Horror  2010
Project X                                                        Comedy  2012
Secret in Their Eyes                                Crime,Drama,Mystery  2015
Hostel: Part II                                                  Horror  2007
Step Up 2: The Streets                              Drama,Music,Romance  2008
Search Party                                           Adventure,Comedy  2014
Nine Lives                                        Comedy,Family,Fantasy  2016

[1000 rows x 2 columns]

### Summary of .loc
- Only uses labels
- Can select rows and columns simultaneously
- Selection can be a single label, a list of labels or a slice of labels
- Put a comma between row and column selections

### Getting started with .iloc
The .iloc indexer is very similar to .loc but only uses integer locations to make its selections. The word .iloc itself stands for integer location so that should help with remember what it does.

In [27]:
movies.iloc[3]

Title                                                              Sing
Genre                                           Animation,Comedy,Family
Description           In a city of humanoid animals, a hustling thea...
Director                                           Christophe Lourdelet
Actors                Matthew McConaughey,Reese Witherspoon, Seth Ma...
Year                                                               2016
Runtime (Minutes)                                                   108
Rating                                                              7.2
Votes                                                             60545
Revenue (Millions)                                               270.32
Metascore                                                            59
Name: 4, dtype: object

In [28]:
movies.iloc[3:6]

,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Rank,,,,,,,,,,,
4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
6,The Great Wall,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.13,42.0

In [29]:
movies_title.iloc[:5]

,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,
Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [30]:
movies_title.iloc[3:4, :3]

,Genre,Description,Director
Title,,,
Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet

## Conditional selections


For example, what if we want to filter our movies DataFrame to show only films directed by Ridley Scott or films with a rating greater than or equal to 8.0?

In [31]:
data = pd.DataFrame({'k1': ['one'] * 3 + ['two'] * 4,
                  'k2': [1, 1, 2, 3, 3, 4, 4]})
data

    k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

In [33]:
data[[True, False, True, False,True, False,True]]

    k1  k2
0  one   1
2  one   2
4  two   3
6  two   4

In [34]:
data.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [35]:
# method that returns a boolean Series indicating whether each row 
# is a duplicate or not
data[data.duplicated()]

    k1  k2
1  one   1
4  two   3
6  two   4

In [36]:
movies['Director']

Rank
1                  James Gunn
2                Ridley Scott
3          M. Night Shyamalan
4        Christophe Lourdelet
5                  David Ayer
6                 Yimou Zhang
7             Damien Chazelle
8                  Sean Foley
9                  James Gray
10              Morten Tyldum
11                David Yates
12             Theodore Melfi
13             Gareth Edwards
14               Ron Clements
15            Nacho Vigalondo
16               Chris Renaud
17                 Mel Gibson
18            Paul Greengrass
19                Garth Davis
20           Denis Villeneuve
21             Stephen Gaghan
22           Kenneth Lonergan
23                  Ben Young
24                 Walt Dohrn
25            Roland Emmerich
26             Dominique Abel
27             S.S. Rajamouli
28             Phillip Guzman
29                  Jon Lucas
30              Justin Kurzel
31               John Hamburg
32                   Tom Ford
33               Bryan Singer
34                 Tim Miller
35         Paul W.S. Anderson
36              Anthony Russo
37          Christopher Nolan
38           Scott Derrickson
39              Antoine Fuqua
40       Patrick Read Johnson
41               Greg Tiernan
42              Barry Jenkins
43              Shawn Burkett
44           John Lee Hancock
45       Ricardo de Montreuil
46               Rob Marshall
47                John Madden
48                Scott Hicks
49                 Justin Lin
50                  Sean Penn
                ...
951       Alfonso Gomez-Rejon
952           Alexander Payne
953      Michael Patrick King
954       Jordan Vogt-Roberts
955        Paul W.S. Anderson
956              Tom Gormican
957             Scott Stewart
958                David Ayer
959                       McG
960             Paul McGuigan
961               Danny Boyle
962           Patricia Rozema
963           Justin Chadwick
964          Steven R. Monroe
965              James Lapine
966               David Lynch
967              Jérôme Salle
968           Robert Zemeckis
969            Micheal Bafaro
970            Gore Verbinski
971           John Luessenhop
972               D.J. Caruso
973             Adam Shankman
974                Wes Craven
975                 Mira Nair
976                Kirk Jones
977     Gilles Paquet-Brenner
978              Lisa Addario
979              Xavier Dolan
980           Pedro Almodóvar
981           Patricia Riggen
982                Will Gluck
983              Julie Taymor
984           Luke Greenfield
985                Boaz Yakin
986        David Gordon Green
987              Steven Quale
988               Shana Feste
989            Pascal Laugier
990              Ava DuVernay
991        Patrick Tatopoulos
992                Aamir Khan
993             Michael Dowse
994        Paul W.S. Anderson
995           Nima Nourizadeh
996                 Billy Ray
997                  Eli Roth
998                Jon M. Chu
999            Scot Armstrong
1000         Barry Sonnenfeld
Name: Director, Length: 1000, dtype: object

In [41]:
condition = (movies['Director'] == "Ridley Scott")

condition

Rank
1       False
2        True
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
30      False
31      False
32      False
33      False
34      False
35      False
36      False
37      False
38      False
39      False
40      False
41      False
42      False
43      False
44      False
45      False
46      False
47      False
48      False
49      False
50      False
        ...
951     False
952     False
953     False
954     False
955     False
956     False
957     False
958     False
959     False
960     False
961     False
962     False
963     False
964     False
965     False
966     False
967     False
968     False
969     False
970     False
971     False
972     False
973     False
974     False
975     False
976     False
977     False
978     False
979     False
980     False
981     False
982     False
983     False
984     False
985     False
986     False
987     False
988     False
989     False
990     False
991     False
992     False
993     False
994     False
995     False
996     False
997     False
998     False
999     False
1000    False
Name: Director, Length: 1000, dtype: bool

In [39]:
condition.mean()

0.008

We want to filter out all movies not directed by Ridley Scott, in other words, we don’t want the False films. To return the rows where that condition is True we have to pass this operation into the DataFrame:

In [42]:
movies[condition]

,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Rank,,,,,,,,,,,
2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
103,The Martian,"Adventure,Drama,Sci-Fi",An astronaut becomes stranded on Mars after hi...,Ridley Scott,"Matt Damon, Jessica Chastain, Kristen Wiig, Ka...",2015,144,8.0,556097,228.43,80.0
388,Robin Hood,"Action,Adventure,Drama","In 12th century England, Robin and his band of...",Ridley Scott,"Russell Crowe, Cate Blanchett, Matthew Macfady...",2010,140,6.7,221117,105.22,53.0
471,American Gangster,"Biography,Crime,Drama","In 1970s America, a detective works to bring d...",Ridley Scott,"Denzel Washington, Russell Crowe, Chiwetel Eji...",2007,157,7.8,337835,130.13,76.0
517,Exodus: Gods and Kings,"Action,Adventure,Drama",The defiant leader Moses rises up against the ...,Ridley Scott,"Christian Bale, Joel Edgerton, Ben Kingsley, S...",2014,150,6.0,137299,65.01,52.0
522,The Counselor,"Crime,Drama,Thriller",A lawyer finds himself in over his head when h...,Ridley Scott,"Michael Fassbender, Penélope Cruz, Cameron Dia...",2013,117,5.3,84927,16.97,48.0
531,A Good Year,"Comedy,Drama,Romance",A British investment broker inherits his uncle...,Ridley Scott,"Russell Crowe, Abbie Cornish, Albert Finney, M...",2006,117,6.9,74674,7.46,47.0
738,Body of Lies,"Action,Drama,Romance",A CIA agent on the ground in Jordan hunts down...,Ridley Scott,"Leonardo DiCaprio, Russell Crowe, Mark Strong,...",2008,128,7.1,182305,39.38,57.0

In [43]:
movies[movies['Director'] == "Ridley Scott"]

,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Rank,,,,,,,,,,,
2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
103,The Martian,"Adventure,Drama,Sci-Fi",An astronaut becomes stranded on Mars after hi...,Ridley Scott,"Matt Damon, Jessica Chastain, Kristen Wiig, Ka...",2015,144,8.0,556097,228.43,80.0
388,Robin Hood,"Action,Adventure,Drama","In 12th century England, Robin and his band of...",Ridley Scott,"Russell Crowe, Cate Blanchett, Matthew Macfady...",2010,140,6.7,221117,105.22,53.0
471,American Gangster,"Biography,Crime,Drama","In 1970s America, a detective works to bring d...",Ridley Scott,"Denzel Washington, Russell Crowe, Chiwetel Eji...",2007,157,7.8,337835,130.13,76.0
517,Exodus: Gods and Kings,"Action,Adventure,Drama",The defiant leader Moses rises up against the ...,Ridley Scott,"Christian Bale, Joel Edgerton, Ben Kingsley, S...",2014,150,6.0,137299,65.01,52.0
522,The Counselor,"Crime,Drama,Thriller",A lawyer finds himself in over his head when h...,Ridley Scott,"Michael Fassbender, Penélope Cruz, Cameron Dia...",2013,117,5.3,84927,16.97,48.0
531,A Good Year,"Comedy,Drama,Romance",A British investment broker inherits his uncle...,Ridley Scott,"Russell Crowe, Abbie Cornish, Albert Finney, M...",2006,117,6.9,74674,7.46,47.0
738,Body of Lies,"Action,Drama,Romance",A CIA agent on the ground in Jordan hunts down...,Ridley Scott,"Leonardo DiCaprio, Russell Crowe, Mark Strong,...",2008,128,7.1,182305,39.38,57.0

**Find how many movies were directed by Christopher Nolan.**

In [51]:
#put your code here
movies[movies['Director'] ==  'Christopher Nolan']

,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Rank,,,,,,,,,,,
37,Interstellar,"Adventure,Drama,Sci-Fi",A team of explorers travel through a wormhole ...,Christopher Nolan,"Matthew McConaughey, Anne Hathaway, Jessica Ch...",2014,169,8.6,1047747,187.99,74.0
55,The Dark Knight,"Action,Crime,Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart,Mi...",2008,152,9.0,1791916,533.32,82.0
65,The Prestige,"Drama,Mystery,Sci-Fi",Two stage magicians engage in competitive one-...,Christopher Nolan,"Christian Bale, Hugh Jackman, Scarlett Johanss...",2006,130,8.5,913152,53.08,66.0
81,Inception,"Action,Adventure,Sci-Fi","A thief, who steals corporate secrets through ...",Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...",2010,148,8.8,1583625,292.57,74.0
125,The Dark Knight Rises,"Action,Thriller",Eight years after the Joker's reign of anarchy...,Christopher Nolan,"Christian Bale, Tom Hardy, Anne Hathaway,Gary ...",2012,164,8.5,1222645,448.13,78.0

Let's look at conditional selections using numerical values by filtering the DataFrame by ratings:

In [52]:
movies[movies['Rating'] >= 8.8]

,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Rank,,,,,,,,,,,
55,The Dark Knight,"Action,Crime,Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart,Mi...",2008,152,9.0,1791916,533.32,82.0
81,Inception,"Action,Adventure,Sci-Fi","A thief, who steals corporate secrets through ...",Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...",2010,148,8.8,1583625,292.57,74.0
118,Dangal,"Action,Biography,Drama",Former wrestler Mahavir Singh Phogat and his t...,Nitesh Tiwari,"Aamir Khan, Sakshi Tanwar, Fatima Sana Shaikh,...",2016,161,8.8,48969,11.15,NaN

We can make some richer conditionals by using logical operators: 
- `|`    for "or"  
- `&`    for "and"


Let's filter the the DataFrame to show only movies by Christopher Nolan OR Ridley Scott:

In [56]:
((movies['Director'] == 'Christopher Nolan') | (movies['Director'] == 'Ridley Scott'))\
&(movies['Revenue (Millions)'] > 1000)

Rank
1       False
2        True
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
30      False
31      False
32      False
33      False
34      False
35      False
36      False
37       True
38      False
39      False
40      False
41      False
42      False
43      False
44      False
45      False
46      False
47      False
48      False
49      False
50      False
        ...
951     False
952     False
953     False
954     False
955     False
956     False
957     False
958     False
959     False
960     False
961     False
962     False
963     False
964     False
965     False
966     False
967     False
968     False
969     False
970     False
971     False
972     False
973     False
974     False
975     False
976     False
977     False
978     False
979     False
980     False
981     False
982     False
983     False
984     False
985     False
986     False
987     False
988     False
989     False
990     False
991     False
992     False
993     False
994     False
995     False
996     False
997     False
998     False
999     False
1000    False
Length: 1000, dtype: bool

In [57]:
movies[(movies['Director'] == 'Christopher Nolan') | (movies['Director'] == 'Ridley Scott')]

,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Rank,,,,,,,,,,,
2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
37,Interstellar,"Adventure,Drama,Sci-Fi",A team of explorers travel through a wormhole ...,Christopher Nolan,"Matthew McConaughey, Anne Hathaway, Jessica Ch...",2014,169,8.6,1047747,187.99,74.0
55,The Dark Knight,"Action,Crime,Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart,Mi...",2008,152,9.0,1791916,533.32,82.0
65,The Prestige,"Drama,Mystery,Sci-Fi",Two stage magicians engage in competitive one-...,Christopher Nolan,"Christian Bale, Hugh Jackman, Scarlett Johanss...",2006,130,8.5,913152,53.08,66.0
81,Inception,"Action,Adventure,Sci-Fi","A thief, who steals corporate secrets through ...",Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...",2010,148,8.8,1583625,292.57,74.0
103,The Martian,"Adventure,Drama,Sci-Fi",An astronaut becomes stranded on Mars after hi...,Ridley Scott,"Matt Damon, Jessica Chastain, Kristen Wiig, Ka...",2015,144,8.0,556097,228.43,80.0
125,The Dark Knight Rises,"Action,Thriller",Eight years after the Joker's reign of anarchy...,Christopher Nolan,"Christian Bale, Tom Hardy, Anne Hathaway,Gary ...",2012,164,8.5,1222645,448.13,78.0
388,Robin Hood,"Action,Adventure,Drama","In 12th century England, Robin and his band of...",Ridley Scott,"Russell Crowe, Cate Blanchett, Matthew Macfady...",2010,140,6.7,221117,105.22,53.0
471,American Gangster,"Biography,Crime,Drama","In 1970s America, a detective works to bring d...",Ridley Scott,"Denzel Washington, Russell Crowe, Chiwetel Eji...",2007,157,7.8,337835,130.13,76.0
517,Exodus: Gods and Kings,"Action,Adventure,Drama",The defiant leader Moses rises up against the ...,Ridley Scott,"Christian Bale, Joel Edgerton, Ben Kingsley, S...",2014,150,6.0,137299,65.01,52.0
522,The Counselor,"Crime,Drama,Thriller",A lawyer finds himself in over his head when h...,Ridley Scott,"Michael Fassbender, Penélope Cruz, Cameron Dia...",2013,117,5.3,84927,16.97,48.0
531,A Good Year,"Comedy,Drama,Romance",A British investment broker inherits his uncle...,Ridley Scott,"Russell Crowe, Abbie Cornish, Albert Finney, M...",2006,117,6.9,74674,7.46,47.0
738,Body of Lies,"Action,Drama,Romance",A CIA agent on the ground in Jordan hunts down...,Ridley Scott,"Leonardo DiCaprio, Russell Crowe, Mark Strong,...",2008,128,7.1,182305,39.38,57.0

** What is the average revenue of all of the movies by Christopher Nolan that have a score of 8.7 or better**

In [58]:
# your code here

all_movies = movies[(movies['Director'] == 'Christopher Nolan') & (movies['Rating'] >=8.7)]

all_movies['Revenue (Millions)'].mean()

412.94500000000005

Using the `isin()` method we could make this more concise though:

In [ ]:
movies[movies['Director'].isin(['Christopher Nolan', 'Ridley Scott'])].head()

Using `~` flips your booleans and allows you to find the inverse of your query.

In [ ]:
movies[~movies['Director'].isin(['Christopher Nolan', 'Ridley Scott'])].head()

## Applied Question: 

Which group of movies has the higher average revenue those with a rating of above 8, or those with at least 300,000 reviews?

In [110]:
# Subset the dataframe to find movies with a rating above 8.
high_rating=movies[movies['Rating']>8]

In [111]:
high_rating.shape

(59, 15)

In [112]:
# Find the average revenue of that group.
high_rating['Revenue (Millions)'].mean()

147.01018181818182

In [113]:
# Subset the dataframe to find movies with more than 300,000 votes.
high_votes=movies[movies['Votes']>300000]

In [114]:
# find the average of that group
high_votes['Revenue (Millions)'].mean()

195.00033333333343

## Data transformation

### Removing duplicates

Duplicate rows may be found in a DataFrame for any number of reasons. Here is an example:

In [60]:
data.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [61]:

data.drop_duplicates()

    k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

If I call `data` again why are there still duplicates?

In [62]:
data

    k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

In [64]:
data.drop_duplicates(inplace=True)

In [66]:
data

    k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

In [67]:
data = pd.DataFrame({'k1': ['one'] * 3 + ['two'] * 4,
                  'k2': [1, 1, 2, 3, 3, 4, 4]})

#we are adding another column to help us understand which row was dropped
data['v1'] = range(7)

data

    k1  k2  v1
0  one   1   0
1  one   1   1
2  one   2   2
3  two   3   3
4  two   3   4
5  two   4   5
6  two   4   6

In [68]:

data.drop_duplicates(['k1'])

    k1  k2  v1
0  one   1   0
3  two   3   3

In [69]:

data.drop_duplicates(['k1'], keep='last')

    k1  k2  v1
2  one   2   2
6  two   4   6

In [70]:
myData = data.drop_duplicates(['k1'], keep='last')

## Create a new column

In [71]:
movies['new_col'] = 0

In [72]:
movies.head()

,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,new_col
Rank,,,,,,,,,,,,
1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,0
2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,0
3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,0
4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,0
5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,0

In [73]:
movies['Votes'].describe()

count    1.000000e+03
mean     1.698083e+05
std      1.887626e+05
min      6.100000e+01
25%      3.630900e+04
50%      1.107990e+05
75%      2.399098e+05
max      1.791916e+06
Name: Votes, dtype: float64

In [75]:
movies['power'] = movies['Rating']* np.log(movies['Votes'])

In [76]:
movies.head()

,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,new_col,power
Rank,,,,,,,,,,,,,
1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,0,109.651452
2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,0,91.655154
3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,0,87.365331
4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,0,79.280224
5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,0,79.877161

## Conditional Transformations

You want to create a new column that shows the revenue for a movie if the movie is longer than 90 minutes or shorter than 190 minutes. 

Given what you knwo about python, how would you go about doing this? 

Write pseudo-code with a partner to come up with the workflow.

In [106]:
%%timeit 
new_list = []
for i in range(movies.shape[0]):
    movie = movies.iloc[i]
    if (movie['Runtime (Minutes)'] > 90) & (movie['Runtime (Minutes)']<190):
        new_list.append(movie['Revenue (Millions)'])
    else: 
        new_list.append(np.nan)
        
movies['new_col'] = new_list

159 ms ± 6.82 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [83]:
movies.head()

,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,new_col,power
Rank,,,,,,,,,,,,,
1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,333.13,109.651452
2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,126.46,91.655154
3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,138.12,87.365331
4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,270.32,79.280224
5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,325.02,79.877161

In [77]:
def apply_time(time, rev):
    if (time > 90) & (time<190):
        return rev
    else: 
        return  np.nan

#### Looping with .itertuples() and .iterrows()
What other approaches can you take? Well, Pandas has actually made the for i in range(len(df)) syntax redundant by introducing the DataFrame.itertuples() and DataFrame.iterrows() methods. These are both generator methods that yield one row at a time.

`.itertuples()` yields a namedtuple for each row, with the row’s index value as the first element of the tuple. A nametuple is a data structure from Python’s collections module that behaves like a Python tuple but has fields accessible by attribute lookup.

`.iterrows()` yields pairs (tuples) of (index, Series) for each row in the DataFrame.

While .itertuples() tends to be a bit faster, let’s stay in Pandas and use .iterrows() in this example, because some readers might not have run across nametuple. Let’s see what this achieves:

In [105]:

def apply_transormation_iterrows(df):
    revenue_list = []
    for index, row in df.iterrows():
        time = row['Runtime (Minutes)']
        rev = row['Revenue (Millions)']
        #use function
        # Append cost list
        revenue = apply_time(time, rev)
        revenue_list.append(revenue)
    df['rev_features'] = revenue_list

%timeit apply_transormation_iterrows(movies)

87.8 ms ± 11.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [98]:
movies.head()

,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,new_col,power,rev_features
Rank,,,,,,,,,,,,,,
1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,333.13,109.651452,333.13
2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,126.46,91.655154,126.46
3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,138.12,87.365331,138.12
4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,270.32,79.280224,270.32
5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,325.02,79.877161,325.02

### Pandas’ .apply()
You can further improve this operation using the .apply() method instead of .iterrows(). Pandas’ .apply() method takes functions (callables) and applies them along an axis of a DataFrame (all rows, or all columns). In this example, a lambda function will help you pass the column of data into apply_time():

In [ ]:
df.apply(
        lambda row: apply_time(
            row['Runtime (Minutes)'],row['Revenue (Millions)']),
        axis=1)

In [109]:
def apply_transformation_withapply(df):
    df['rev_features_a'] = df.apply(
        lambda row: apply_time(
            row['Runtime (Minutes)'],row['Revenue (Millions)']),
        axis=1)

%timeit apply_transformation_withapply(movies)

19.3 ms ± 3.61 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)